export const workDetails = [
  {
    title: "Battalion Admin",
    type: "Website Design",
    subtitle: "Comprehensive control center for managing users and devices",
    image:
      "https://res.cloudinary.com/dmufwerzv/image/upload/v1728656978/admin_jjfbrx.png",
    tags: ["Next.js", "Admin", "Dashboard"],
    buttonText: "Explore Work",
    about: {
      images: [
        "https://res.cloudinary.com/dmufwerzv/image/upload/v1729092571/admin1_en1vt3.png",
        "https://res.cloudinary.com/dmufwerzv/image/upload/v1729140048/admintwo_xwrkvl.png",
        "https://res.cloudinary.com/dmufwerzv/image/upload/v1729140047/admin3_cbqlpo.png",
        "https://res.cloudinary.com/dmufwerzv/image/upload/v1729140051/admin4_jlkery.png",
      ],
      title: "",
      desc: "The Battalion Admin Panel, built using Next.js, is a robust management interface designed to oversee devices and users for the Battalion tool platform. This admin panel is central to maintaining and controlling key functionalities of the Battalion ecosystem, which provides secure tools and solutions for device management and optimization.",
      keyfeatures: [
        "User Management: Easily add, update, or remove users and manage access permissions.",
        "Device Control: Monitor, remove devices, and view users connected to each device.",
        "Real-Time Updates: Get live insights on user activities and device statuses.",
        "Search Function: Quickly find specific users or devices with the built-in search feature.",
        "Pagination: Easily navigate large datasets of users and devices with paginated views.",
        "Secure Access: Protect the panel with strong authentication and role-based permissions.",
        "Responsive Design: Intuitive interface that works smoothly across all device types.",
        "Notifications: Receive real-time alerts for key actions and system events.",
        "Scalability: Efficiently manage increasing numbers of users and devices as the platform grows.",
      ],
      responsibility: [
        "Design Implementation: I meticulously translated the design from Figma into a fully functional interface, ensuring that all visual elements adhered closely to the original specifications.",
        "Functionality Development: I developed all essential functionalities of the admin panel, enabling seamless management of users and devices.",
        "Custom Resizable Table: I implemented a custom resizable table feature that mimics spreadsheet functionality, allowing users to adjust column widths dynamically for a more tailored data presentation.",
        "User Experience Optimization: I ensured that the interface is intuitive and responsive, providing a smooth experience across various device types.",
      ],
    },
  },
  {
    title: "Cramers Uniform",
    type: "Website Design",
    subtitle: "Optimized ecommerce for school uniforms.",
    image:
      "https://res.cloudinary.com/dmufwerzv/image/upload/v1728641594/cramers_zqgibr.png",
    tags: ["Shopify", "B2C", "Ecommerce"],
    buttonText: "Explore Work",
    about: {
      images: [
        "https://res.cloudinary.com/dmufwerzv/image/upload/v1729163266/first_ep9eid.png",
        "https://res.cloudinary.com/dmufwerzv/image/upload/v1729163267/two_h10kyf.png",
        "https://res.cloudinary.com/dmufwerzv/image/upload/v1729163267/three_y3c52p.png",
        "https://res.cloudinary.com/dmufwerzv/image/upload/v1729163266/four_ilrnwd.png",
        "https://res.cloudinary.com/dmufwerzv/image/upload/v1729163617/five_fo3x7j.png",
        "https://res.cloudinary.com/dmufwerzv/image/upload/v1729163826/six_q20q6m.png",
      ],
      title: "Cramers Uniforms",
      desc: "Cramers Uniforms is an online store specializing in school uniforms, offering apparel for students across Philadelphia. With over 95 years of service, the store provides high-quality uniforms and accessories tailored to school-specific needs",
      keyfeatures: [
        "School-Specific Uniform Search: Allows users to easily find uniforms based on their school.",
        "Product Catalog: Features a well-organized selection of various categories, including shirts, pants, gym wear, and shoes, allowing users to easily find what they need.",
        "Custom School Orders: Schools can place bulk orders directly.",
        "Pop-up Shops: Provides in-person shopping events at schools.",
        "Discounts and Promotions: Prominently featured for users.",
        "User-Friendly Navigation: Clean interface with easy-to-navigate product listings.",
      ],
      responsibility: [
        "Developed the Cramers Uniforms website using Shopify, ensuring a seamless user experience and efficient navigation.",
        "Implemented designs from Figma, translating visual concepts into functional web pages.",
        "Configured product categories and school-specific uniform searches to enhance user accessibility.",
        "Managed custom school order features and pop-up shop integrations.",
        "Integrated interactive maps to assist users in locating pop-up shop events.",
        "Collaborated with stakeholders to ensure alignment with branding and usability goals.",
      ],
    },
  },
  {
    title: "Battalion App",
    type: "Mobile App Design",
    subtitle: "Efficient Tool Management with Advanced Mobile Solutions",
    image:
      "https://res.cloudinary.com/dmufwerzv/image/upload/v1728639180/mobile1_u4sgpn.png",
    tags: ["React Native", "Cross-Platform"],
    buttonText: "Explore Work",
    about: {
      images: [
        "https://res.cloudinary.com/dmufwerzv/image/upload/v1729148102/mock1_qmno4c.png",
        "https://res.cloudinary.com/dmufwerzv/image/upload/v1729148030/mock2_qgmcue.png",
        "https://res.cloudinary.com/dmufwerzv/image/upload/v1729149078/mock3_jid5sb.png",
        "https://res.cloudinary.com/dmufwerzv/image/upload/v1729148609/mock4_phmawe.png",
      ],
      title: "",
      desc: "Battalion mobile app is designed to streamline tool management for professionals in construction and maintenance. By leveraging advanced mobile solutions, the app enables users to efficiently track, manage, and organize their tools both on-site and in the shop. Featuring a user-friendly interface built with React Native, the app supports cross-platform functionality, ensuring accessibility for all users.",
      keyfeatures: [
        "Real-time Tool Monitoring: Users can keep track of their tools’ status and locations.",
        "Custom Configuration: The app allows for personalized settings tailored to individual user needs.",
        " Seamless Integration: Works in tandem with smart toolbox products to enhance productivity.",
      ],
      responsibility: [
        "Developed the user interface for all screens in accordance with the Figma prototypes.",
        "Combined phone number and email authentication as part of the app's authorization features",
        "Developed a structured Firestore database for effective tool management.",
        "Created data models for combined serial numbers and device IDs.",
        "Integrated user management features for real-time data updates.",
        "Ensured scalability and responsiveness through Firebase Firestore integration.",
      ],
    },
  },
  {
    title: "Battalion Tools",
    type: "Website Design",
    subtitle: "Streamlined Tool Management for Military and Industrial Use",
    image:
      "https://res.cloudinary.com/dmufwerzv/image/upload/v1728639499/heat1_vc7ndm.png",
    tags: ["Shopify", "B2B", "B2C", "Ecommerce"],
    buttonText: "Explore Work",
    about: {
      images: [
        "https://res.cloudinary.com/dmufwerzv/image/upload/v1729159765/first_da3y1a.png",
        "https://res.cloudinary.com/dmufwerzv/image/upload/v1729161284/second_dwztrd.png",
        "https://res.cloudinary.com/dmufwerzv/image/upload/v1729161284/three_fml1x1.png",
        "https://res.cloudinary.com/dmufwerzv/image/upload/v1729161284/four_mmbtak.png",
        "https://res.cloudinary.com/dmufwerzv/image/upload/v1729161284/five_yhdtt4.png",
        "https://res.cloudinary.com/dmufwerzv/image/upload/v1729161284/six_gew80l.png",
        "https://res.cloudinary.com/dmufwerzv/image/upload/v1729161284/mobview_znaoub.png",
      ],
      title: "Next-Gen Tool Management",
      desc: "Battalion Tool offers two advanced smart toolbox variants: Rover and Rover Heat. Both models feature smart locks, LED lighting, and durable all-terrain wheels, with Rover Heat providing heated compartments for use in extreme conditions. Equipped with USB-A/C ports, 120V outlets, and smartphone connectivity, these toolboxes are designed for tough industrial and military environments, offering cutting-edge convenience and functionality.",
      keyfeatures: [
        "Heated compartments",
        "Smart locking mechanisms",
        "Interior LED lighting",
        "Smartphone connectivity",
        "USB-A/C and 120V outlets",
        "Durable all-terrain wheels",
      ],
      responsibility: [
        "Developed a responsive eCommerce site using Shopify",
        "Designed custom user interfaces for the smart toolbox features",
        "Optimized for mobile and desktop experiences",
        "Implemented payment options and ensured smooth checkout processes",
        "Enhanced site performance and SEO for better user engagement",
      ],
    },
  },
  {
    title: "Phone Sentrix",
    type: "Website Design",
    subtitle: "Stylish, durable ecommerce for phone covers.",
    image:
      "https://res.cloudinary.com/dmufwerzv/image/upload/v1728660257/phone_centrix_iamxhd.jpg",
    tags: ["Next.js", "B2C", "Ecommerce"],
    buttonText: "Explore Work",
    about: {
      images: [
        "https://res.cloudinary.com/dmufwerzv/image/upload/v1729133016/one_nfsmtz.png",
        "https://res.cloudinary.com/dmufwerzv/image/upload/v1729134003/four_sklvtp.png",
        "https://res.cloudinary.com/dmufwerzv/image/upload/v1729133570/three_d824wk.png",
        "https://res.cloudinary.com/dmufwerzv/image/upload/v1729133332/two_milbhe.png",
        "https://res.cloudinary.com/dmufwerzv/image/upload/v1729134162/five_cfw36k.png",
      ],
      title: "Phone Sentrix",
      desc: "Phone Sentrix is an e-commerce platform specializing in mobile phone covers. It offers a wide range of stylish and protective cases for various smartphone brands, focusing on quality, durability, and design. With a user-friendly interface and affordable pricing, Phone Sentrix provides customers with the perfect blend of functionality and fashion for their mobile devices. ",
      keyfeatures: [
        "Responsive Design: Ensuring the platform works seamlessly across devices, from smartphones to desktops.",
        "Secure Payment Integration: Incorporating trusted payment gateway (UPS) for secure transactions.",
        "Advanced Product Filtering: Options to filter products by brand, material, and price range.",
        "Wishlists & Favorites: Enabling users to save products for future purchases",
        "SEO Optimization: Ensuring the platform is optimized for search engines to drive organic traffic.",
      ],
      responsibility: [
        "Built all website pages based on Figma designs, ensuring pixel-perfect implementation.",
        "Integrated API endpoints from Swagger to display products and handle various e-commerce functionalities.",
        "Developed product sorting features (price: A-Z, Z-A, high to low) and showcased recent, related, and most sold products.",
        "Implemented pagination and search functionality for seamless product browsing.",
        "Managed all core e-commerce features, including product filtering and dynamic content loading.",
      ],
    },
  },
];
